name: esae

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - numpy
  - rich
  - pyarrow
  - mypy
  - aiofiles
  - aiohttp
  - transformers
  - pytest
  - pytest-asyncio
  - types-aiofiles
  - attrs
  - wandb
  - faiss-gpu=1.8.0
  - blobfile
  - elasticsearch=8.15.1
  - pillow
  - seaborn
  - sentencepiece
  - pip:
      - treevizer
      - flash-attn
